{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" $ }}-{{ $name }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    app: {{ $name }}
spec:
  replicas: {{ $service.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" $ | nindent 6 }}
      app: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" $ | nindent 8 }}
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          imagePullPolicy: {{ $service.image.pullPolicy }}
          ports:
            - containerPort: {{ $service.service.port }}
              name: http
          {{- if $service.env }}
          env:
            {{- toYaml $service.env | nindent 12 }}
          {{- end }}
          {{- if $service.volumeMounts }}
          volumeMounts:
            {{- toYaml $service.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if $service.volumes }}
      volumes:
        {{- toYaml $service.volumes | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
