{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" $ }}-{{ $name }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    app: {{ $name }}
spec:
  type: {{ $service.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" $ | nindent 4 }}
    app: {{ $name }}
{{- end }}
{{- end }}
