apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-app-pv
spec:
  storageClassName: go-app-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
