apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-app-pvc
  namespace: dev
spec:
  storageClassName: go-app-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
