package: api
output: api/api.gen.user.go
generate:
  - types
  - server
  - client
include-tags:
  - users
import-mapping:
  ../schema/Response.yaml: "-"
  ../schema/User.yaml: "-"
  ../request/userCreate.yaml: "-"
  ../request/userUpdate.yaml: "-"
  ../path/user.yaml: "-"
  ../path/userWithId.yaml: "-"
