name: Act test ci, cd

on:
  pull_request:
    paths:
      - 'act-test/**'

env:
  working-dir: ./.github/workflows
  dir: ./act-test

jobs:
  test:
    name: Go CI/CD
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Run go test
        working-directory: ${{ env.dir }}
        run: go test ./...
  lint:
    name: Go lint
    uses: ${{ env.working-dir }}/reusable/reusable-lint.yaml
    with:
      from: ${{ env.working-dir }}/act-test-ci.yaml
      dir: ${{ env.dir }}